version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /home/BC1
    command: python3 /home/BC1/server.py -p 5000 -a "0.0.0.0"

  web2:
    image: blockchain_web
    ports:
      - "5001:5001"
    volumes:
        - /home/BC1
    command: python3 /home/BC1/server.py -p 5001 -a "0.0.0.0"

  web3:
    image: blockchain_web
    ports:
      - "5002:5002"
    volumes:
      - /home/BC1
    command: python3 /home/BC1/server.py -p 5002 -a "0.0.0.0"