# 打印版本的信息，没啥大用
version: "3"

services:
  web1:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /home/BC1
    command: python3 /home/BC1/server.py -p 5000

  web2:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
    volumes:
        - /home/BC1
    command: python3 /home/BC1/server.py -p 5001

  web3:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - /home/BC1
    command: python3 /home/BC1/server.py -p 5002